services:
  poller:
    build: .
    env_file:
      - .env
    environment:
      - DB_HOST=postgres
    depends_on:
      - postgres
    command: bash -c "uv run alembic upgrade head && uv run python -m events_poller.poller.run"
  api:
    build: .
    env_file:
      - .env
    environment:
      - DB_HOST=postgres
    depends_on:
      - postgres
    ports:
      - 8000:8000
    command: "uv run uvicorn events_poller.api.app:app --host 0.0.0.0 --port 8000"
  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=events_poller
    ports:
      - 5432:5432
