"""make event_id column unique

Revision ID: fb41dcc7e934
Revises: bc22f5133ce4
Create Date: 2025-09-06 18:15:24.237501

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "fb41dcc7e934"
down_revision: Union[str, Sequence[str], None] = "bc22f5133ce4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "events", ["event_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "events", type_="unique")
    # ### end Alembic commands ###
